### ISSUE TITLE
Autograder: Not Running

### ISSUE THREAD

**Issue by qdm097** [comp426-2023-spring/a04#1]
#### Which autograder check is failing?

All checks under education/autograding/@v1, but more specifically Node version, which really should never fail.

#### What is happening?

::error::The output for test Node version did not match%0AExpected:%0A{"player":"(rock|paper|scissors)","opponent":"(rock|paper|scissors)","result":"(win|lose|tie)"}%0AActual:%0Av18.14.2

My application returns the node version but the expected return is an rps return.

#### Failed workflow run URL

https://github.com/comp426-2023-spring/a04-qdm097/actions/runs/4368485571/jobs/7641131889

#### What should be happening?

The check should pass considering my application returns the correct version. I suspect this is an autograder config issue.

#### Screenshots of your local test(s)

I certainly could submit this, but the autograder itself is not running, so I'm not really sure how applicable this is.

#### Why do you think the autograder is failing? 

I assume the call to my code is misconfigured. Literally all other assignments pass this check with something like "v18.14.1" returned. The other assignments actually pass this check even if nothing is submitted and on initial configuration.

**Comment by qdm097** [comment]
Rename to something meaningful

**Comment by daqichen** [comment]
@qdm097 Looking into the autograder, you are correct that the `node version` test should not fail

**Comment by daqichen** [comment]
It has been fixed! Closing Issue now
